export const SET_ENVELOPE_ATTACK = 'SET_ENVELOPE_ATTACK';
export const SET_ENVELOPE_DECAY = 'SET_ENVELOPE_DECAY';
export const SET_ENVELOPE_SUSTAIN = 'SET_ENVELOPE_SUSTAIN';
export const SET_ENVELOPE_HOLD = 'SET_ENVELOPE_HOLD';
export const SET_ENVELOPE_RELEASE = 'SET_ENVELOPE_RELEASE';
